#!/usr/bin/env python3
"""
Fix math mode issues in LaTeX files generated by nbconvert.
Converts (command) patterns to \(command\) when they should be in math mode.
"""

import re
import sys


def fix_latex_math(latex_file: str) -> None:
    """Fix math mode issues in generated LaTeX."""
    with open(latex_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    original = content
    
    # Fix common patterns where math commands appear outside math mode
    # Pattern: (command) where command is a math symbol/function
    math_commands = [
        r'\\min', r'\\max', r'\\sum', r'\\in', r'\\gamma', r'\\leq', r'\\geq',
        r'\\sim', r'\\cdot', r'\\times', r'\\div', r'\\pm', r'\\mp'
    ]
    
    # Fix patterns like (D\sim) -> \(D\sim\)
    for cmd in math_commands:
        # Pattern: (text\command) -> \(text\command\)
        pattern = r'\(([^)]*?' + cmd + r'[^)]*?)\)'
        replacement = r'\(\1\)'
        content = re.sub(pattern, replacement, content)
    
    # Fix specific common patterns
    fixes = [
        # (D\sim\text{...}) -> \(D\sim\text{...}\)
        (r'\(D\\sim\\text\{Unif\}', r'\(D\sim\text{Unif}'),
        # (s\in\{...\}) -> \(s\in\{...\}\)
        (r'\(s\\in\{', r'\(s\in\{'),
        # (\gamma=...) -> \(\gamma=...\)
        (r'\(\\gamma=', r'\(\gamma='),
        # (s) when it's clearly a variable -> \(s\)
        (r'\b\(s\)\b(?!\s*is)', r'\(s\)'),
        # (a) when it's clearly a variable -> \(a\)
        (r'\b\(a\)\b(?!\s*is)', r'\(a\)'),
    ]
    
    for pattern, replacement in fixes:
        content = re.sub(pattern, replacement, content)
    
    # Fix {[} ... {]} display math issues
    # {[} should be \[ and {]} should be \]
    content = re.sub(r'\{\[\}', r'\\[', content)
    content = re.sub(r'\{\]\}', r'\\]', content)
    
    if content != original:
        with open(latex_file, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Fixed math mode issues in {latex_file}")
    else:
        print(f"No math mode issues found in {latex_file}")


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <latex_file.tex>")
        sys.exit(1)
    
    fix_latex_math(sys.argv[1])
